### ISSUE TITLE
Can't call method "end" on unblessed reference

### ISSUE THREAD

**Issue by jreisinger** [yanick/cheatsheets#1]
Hello,

I tried out mkd_cheatsheet.pl on one of my documents written in MarkDown - https://github.com/jreisinger/blog/blob/master/posts/lvm.md:

```
$ perl /tmp/mkd_cheatsheet.pl posts/login-scripts.md posts/lvm.md 
Can't call method "end" on unblessed reference at /home/jreisinger/perl5/lib/perl5/Web/Query.pm line 286.
```

**Comment by yanick** [comment]
That's actually a bug with Web::Query. I found the cause, and a new version should flow toward CPAN in the next few hours.

**Comment by yanick** [comment]
There, new version of Web::Query sent to CPAN, and should help.
